name: AI-Enhanced CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install pandas scikit-learn requests

      - name: Run AI failure predictor
        run: python ai/failure_predictor.py

      - name: Debug workspace
        run: ls -R

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Run tests
        run: echo "✅ Tests passed successfully"

      - name: Deploy (simulation)
        run: echo "🚀 Deployment successful"
